spring.application.name=cinemahub
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_db
spring.datasource.username=cinema_user
spring.datasource.password=cinema123

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
